#!/usr/bin/env python3
"""generate_machi.py — generate the "Machi" room (a quaint Japanese town) and
the "Konbini" shop interior behind its 7-Eleven door.

Composition-only: all machinery lives in tools/roomgen.py, and every object
comes from the Tiled-authored prefab library (tiled/prefabs/*.tmj — edit them
in the Tiled app). Deterministic and idempotent: rebuilds rooms.Machi and
rooms.Konbini from scratch each run, leaves other rooms alone, and (once)
adds the Tokyo road transporters.

Run from gamev2/:  python3 tools/generate_machi.py
Then:              python3 tools/qa_port.py --room Machi   (and --room Konbini)
                   python3 tools/config_to_tiled.py Machi  (and Konbini, Tokyo)
"""
import random
import roomgen as rg
from roomgen import rect

cfg = rg.load_config()

# =============================== MACHI =======================================
b = rg.Builder(48, 34)
rng = random.Random(7)

b.fill('grass-autotile')

plaza_shrine = rect(20, 2, 29, 8)
approach = rect(22, 9, 25, 14)
street = rect(3, 15, 45, 16)
plaza_south = rect(19, 18, 30, 24)
lane = rect(23, 17, 24, 17)
road_east = rect(31, 20, 47, 21)
path_garden = rect(4, 22, 18, 23)

b.autotile('flat-grey-brick-autotile', plaza_shrine + approach + lane)
b.autotile('grey-brick-autotile', street)
b.autotile('light-concrete-autotile', plaza_south)
b.autotile('gravel-autotile', road_east + path_garden)

for (fx, fy) in [(14, 6), (43, 8), (5, 26), (15, 26), (34, 25)]:
    b.flowers(fx, fy)

b.pond(5, 7, 10)
b.pond(36, 6, 41)

# borders
for x in (2, 7, 12, 33, 38, 43): b.stamp('sakura-large', x, 0)
for x in (3, 8, 13, 18, 23, 28, 33, 38, 43): b.stamp('sakura-large', x, 30)
for y in range(2, 29, 3): b.stamp('shrub-large', 0, y)
for y in range(2, 29, 3):
    if not (18 <= y <= 21): b.stamp('shrub-large', 46, y)
b.stamp('shrub-small', 46, 19); b.stamp('shrub-small', 46, 22)

# shrine precinct
b.stamp('shrine', 23, 1)
b.stamp('fox-statue', 21, 4); b.stamp('fox-statue', 27, 4)
b.stamp('bell-blue', 29, 1)
b.stamp('lantern-red', 20, 6); b.stamp('lantern-red', 28, 6)
b.stamp('lantern-red', 21, 10); b.stamp('lantern-red', 26, 10)
b.stairs(23, 9); b.stairs(24, 9)
b.stamp('torii-red', 21, 11)
b.plants(19, 8, 1); b.plants(30, 8, 2)

# sakura park (top-left)
b.stamp('sakura-large', 4, 2); b.stamp('sakura-large', 9, 3); b.stamp('sakura-large', 13, 2)
b.stamp('sakura-small', 3, 6); b.stamp('sakura-small', 15, 4)
b.stamp('shrub-small', 12, 8); b.plants(4, 6, 0); b.plants(11, 5, 3); b.plants(13, 9, 2)

# east garden (top-right)
b.stamp('tree-green', 34, 2); b.stamp('tree-green', 41, 2); b.stamp('tree-green', 37, 9)
b.stamp('sakura-small', 44, 4); b.stamp('shrub-small', 35, 8); b.plants(42, 9, 1); b.plants(33, 5, 0)

# street lamps (kept clear of the shop fronts and house footprints)
for x in (6, 34): b.stamp('lamp-blue', x, 14)
for x in (9, 15, 27, 37, 43): b.stamp('lamp-blue', x, 17)

# shop row: the 7-Eleven's door stays OPEN and leads into the Konbini room
konbini_door = b.stamp('seven-eleven', 7, 11, seal=False)[0]
b.stamp('sign-7-11', 10, 12)
b.stamp('vending-white', 12, 13); b.stamp('vending-red', 14, 13); b.stamp('vending-white', 16, 13)
b.stamp('sakura-small', 18, 12)

# houses (doors sealed — no interiors for these yet)
b.stamp('house-blue', 28, 11)
b.stamp('house-black', 33, 10)
b.stamp('house-red', 38, 11)
b.stamp('house-blue', 43, 11)
for hx in (29, 34, 39, 44):
    b.put('Over Floor', hx, 15, 'tile-brick-path_2_1')

# south plaza
b.stamp('pagoda-small', 24, 19)
for i, (px, py) in enumerate([(21, 19), (28, 19), (21, 23), (28, 23),
                              (22, 21), (27, 21), (23, 24), (26, 24)]):
    b.paver(px, py, i)
b.stamp('vending-red', 30, 18); b.stamp('vending-white', 19, 18)
b.stamp('lantern-red', 20, 16); b.stamp('lantern-red', 29, 16)
b.stamp('lantern-red', 20, 24); b.stamp('lantern-red', 29, 24)
b.plants(22, 18, 0); b.plants(27, 18, 3); b.plants(20, 21, 2); b.plants(29, 22, 1)

# orchard + garden (south-west)
for ox in (5, 8, 11, 14):
    for oy in (20, 24):
        b.stamp('sakura-small', ox, oy)
b.plants(6, 22, 0); b.plants(9, 23, 1); b.plants(12, 22, 2); b.plants(15, 23, 3); b.plants(7, 26, 1)

# east road lanterns + greenery south of the houses
b.stamp('lantern-red', 44, 18); b.stamp('lantern-red', 44, 22)
b.stamp('sakura-small', 34, 17); b.stamp('sakura-small', 40, 17)
b.stamp('shrub-small', 37, 18); b.stamp('shrub-small', 42, 18); b.plants(35, 18, 1); b.plants(38, 17, 2)

# south fence line
for i, x in enumerate(range(3, 45)):
    if x in (23, 24): continue
    b.fence(x, 28, i)

# scattered plants
for i in range(14):
    sx, sy = rng.randrange(3, 45), rng.randrange(17, 27)
    if all(f'{sx},{sy}' not in b.L[n] for n in ('Collidables', 'Colliders', 'Over Floor', 'Other')) \
       and rg._pal[b.L['Floor'][f'{sx},{sy}']].startswith('grass'):
        b.plants(sx, sy, i)

dylan = rg.make_npc('Dylan', 'dylan', 27, 22, [
    "Hello! I'm Dylan.",
    "A whole town, generated by one script.",
    "...I still bet it would've been better in Godot."
])
cfg['rooms']['Machi'] = b.room('Machi', npcs=[dylan], transporters=[
    rg.transporter(47, 20, 'Tokyo', 3, 41),
    rg.transporter(47, 21, 'Tokyo', 3, 42),
    # the 7-Eleven doorway (prefab door point, left open by seal=False)
    rg.transporter(konbini_door[0], konbini_door[1], 'Konbini', 9, 13, hidden=True),
])

# =============================== KONBINI =====================================
kb = rg.Builder(20, 15)
kb.autotile('light-concrete-autotile', rect(0, 0, 19, 14))
for rx in (9, 10):
    for ry in range(7, 14):
        kb.put('Over Floor', rx, ry, 'tile-brick-path_2_1')

# walls: stone across the top and bottom (door gap), panelled sides
for x in range(20):
    kb.wall_stone(x, 0)
for y in (2, 4, 6, 8, 10, 12):
    for x in (0, 19):
        kb.wall_panel(x, y)
for x in range(1, 19):
    if x in (9, 10): continue
    kb.wall_stone(x, 13)

# aisles: vending "coolers" against the back wall, a counter, lanterns
for x in (3, 4, 5): kb.stamp('vending-white', x, 2)
for x in (14, 15, 16): kb.stamp('vending-red', x, 2)
kb.counter(9, 5)
kb.stamp('lantern-red', 1, 11); kb.stamp('lantern-red', 18, 11)
kb.paver(9, 14, 0); kb.paver(10, 14, 1)   # door mat

outside = (konbini_door[0], konbini_door[1] + 1)   # cell in front of the 7-Eleven door
cfg['rooms']['Konbini'] = kb.room('Konbini', transporters=[
    rg.transporter(9, 14, 'Machi', outside[0], outside[1], hidden=True),
    rg.transporter(10, 14, 'Machi', outside[0], outside[1], hidden=True),
])

# =============================== WIRING ======================================
tok = cfg['rooms']['Tokyo']['transporters']
if not any(t.get('targetRoom') == 'Machi' for t in tok):
    tok.append(rg.transporter(1, 41, 'Machi', 45, 20))
    tok.append(rg.transporter(1, 42, 'Machi', 45, 21))

rg.save_config(cfg)
print(f"Machi {b.W}x{b.H} + Konbini {kb.W}x{kb.H}; 7-Eleven door at {konbini_door} -> Konbini")
