name: "Godot CI/CD Export and Deploy"
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GODOT_VERSION: 3.6
  PROJECT_PATH: "."

jobs:
  export-web-and-deploy:
    name: Web Export and Firebase Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.6
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup and Build
        run: |
          mkdir -v -p public
          apt-get update && apt-get install -y wget
          wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          dpkg -i packages-microsoft-prod.deb
          apt-get update && apt-get install -y dotnet-sdk-7.0
          godot --headless --verbose --editor --quit
          dotnet build game.sln
          
      - name: Web Build
        run: |
          godot --headless --verbose --export "HTML5" ./public/index.html 
          
      - name: Install Node.js and npm
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs
          node --version
          npm --version
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVHOUSE_80936 }}'
          channelId: live
          projectId: devhouse-80936
          target: devhouse-80936
